_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 12
                - 45
                - 55
                - 105
            "2":
                - 12
                - 45
                - 55
                - 105
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": darwin-arm64
BUFFER_BATCH_SIZE:
    value: 128
BUFFER_SIZE:
    value: 10000
ENTITY:
    value: imsinha-harvard-university
EPSILON_ANNEAL_TIME:
    value: 250000
EPSILON_FINISH:
    value: 0.05
EPSILON_START:
    value: 1
GAMMA:
    value: 0.99
LEARNING_STARTS:
    value: 10000
LR:
    value: 0.00025
LR_LINEAR_DECAY:
    value: false
NUM_ENVS:
    value: 10
NUM_SEEDS:
    value: 1
PROJECT:
    value: HouseMaze
SEED:
    value: 0
TARGET_UPDATE_INTERVAL:
    value: 500
TAU:
    value: 1
TOTAL_TIMESTEPS:
    value: 500000
TRAINING_INTERVAL:
    value: 10
WANDB_MODE:
    value: online
